# date and time
import datetime

just_now = datetime.datetime.now()
print(f"Y: {just_now: %Y}")
print(f"{just_now}")
print(f"m: {just_now: %m}")
print(f"d: {just_now: %d}")
print(f"H: {just_now: %H}")
print(f"M: {just_now: %M}")
print(f"S: {just_now: %S}")
print(f"f: {just_now: %f}")
print(f"w: {just_now: %w}")
print(f"A: {just_now: %A}")
print(f"a: {just_now: %a}")
print(f"U: {just_now: %U}")
print(f"W: {just_now: %W}")
print(f"c: {just_now: %c}")
print(f"x: {just_now: %x}")
print(f"X: {just_now: %X}")
print(f"j: {just_now: %j}")
print(f"p: {just_now: %p}")
print(f"r: {just_now: %r}")
print(f"R: {just_now: %R}")
print(f"f: {just_now: %f}")
print(f"F: {just_now: %F}")
print(f"w: {just_now: %w}")
print(f"W: {just_now: %W}")
print(f"U: {just_now: %U}")
print(f"V: {just_now: %V}")
print(f"G: {just_now: %G}")
print(f"g: {just_now: %g}")
print(f"C: {just_now: %C}")
print(f"y: {just_now: %y}")
